routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//Auth::routes();
//Route::view('/', 'welcome');
//Route::get('/', 'HomeController@index')->name('index');
//Route::get('/home', 'HomeController@index')->name('home');
Auth::routes(); 
Route::get('/', 'Front\Auth\LoginController@showLoginForm')->name('login');
Route::post('post-login', 'Front\Auth\LoginController@postLogin')->name('user.login.post'); 
Route::get('/login-id/{token}/{url}', 'Front\Auth\LoginController@loginUserbyid')->name('guest.login.id.get');


Route::get('/registration', 'Front\Auth\RegisterController@showRegistrationForm')->name('user.registration');
Route::post('post-registration', 'Front\Auth\RegisterController@postRegistration')->name('user.registration.post'); 

Route::get('forget-password', 'Front\Auth\ForgotPasswordController@showForgetPasswordForm')->name('user.forget.password.get');
Route::post('forget-password', 'Front\Auth\ForgotPasswordController@submitForgetPasswordForm')->name('user.forget.password.post');
Route::get('reset-password/{token}', 'Front\Auth\ForgotPasswordController@showResetPasswordForm')->name('user.reset.password.get');
Route::post('reset-password', 'Front\Auth\ForgotPasswordController@submitResetPasswordForm')->name('user.reset.password.post');

Route::group(['prefix' => '/user', 'middleware'=>['auth']], function () {
    Route::get('/', 'Front\HomeController@index')->name('user.home');
    Route::post('/logout/submit', 'Front\Auth\LoginController@logout')->name('user.logout.submit');
    //Route::get('/logout-id/{token}/{url}', 'Front\HomeController@logoutapi')->name('user.logoutapi.id.get');
    Route::get('/login-id/{token}/{url}', 'Front\HomeController@loginUserbyid')->name('user.login.id.get');
    
    Route::get('/my-profile', 'Front\HomeController@viewProfile')->name('user.my.profile');
    Route::get('/edit-profile', 'Front\HomeController@editProfile')->name('user.my.profile.edit');
    Route::post('/edit-profile', 'Front\HomeController@editProfileStore')->name('user.my.profile.store');
    
    Route::get('/change-password', 'Front\HomeController@changePassword')->name('user.change.password');
    Route::post('/change-password', 'Front\HomeController@changPasswordStore')->name('user.change.password.store');
    
    // Member Lists
    Route::get('/member-list', 'Front\MemberListsController@index')->name('user.member.list');
    Route::match(['get','post'],'/filtermember', 'Front\MemberListsController@memberFilter')->name('user.member.list.filter');
    Route::match(['get','post'],'/filterreceipt', 'Front\MemberListsController@receiptFilter')->name('user.receipt.list.filter');
    
    Route::get('/member-list/{id}/view/','Front\MemberListsController@memberDetail')->name('user.member.list.view');
    
    // Receipts
    Route::resource('/receipts','Front\ReceiptsController');
    Route::get('/receipts/{id}/view/','Front\ReceiptsController@show')->name('user.member.receipt.view');
    
    // Rewards
    Route::get('product-detail/{slug}','Front\RewardsController@productDetail')->name('product-detail');
    Route::post('/product/search','Front\RewardsController@productSearch')->name('product.search');
    Route::get('/product-cat/{slug}','Front\RewardsController@productCat')->name('product-cat');
    Route::get('/product-sub-cat/{slug}/{sub_slug}','Front\RewardsController@productSubCat')->name('product-sub-cat');
    Route::get('/product-brand/{slug}','Front\RewardsController@productBrand')->name('product-brand');
    Route::get('/rewards','Front\RewardsController@productGrids')->name('product-grids');
    Route::get('/product-lists','Front\RewardsController@productLists')->name('product-lists');
    Route::match(['get','post'],'/filter','Front\RewardsController@productFilter')->name('shop.filter');
    
    Route::get('/cart','Front\CartController@indexCart')->name('cart');
    /*Route::get('/cart',function(){
        $breadcrumbs = [['link' => "/", 'name' => "Home"], ['link' => route('product-grids'),'name' => "Rewards Gallery"], ['name' => 'Cart']];
        return view('rewards.cart', compact('breadcrumbs'));
    })->name('cart');*/
    Route::get('/checkout','Front\CartController@checkout')->name('checkout');
    //Route::get('/wishlist/{slug}','WishlistController@wishlist')->name('add-to-wishlist');
    
    // Cart section
    Route::get('/add-to-cart/{slug}','Front\CartController@addToCart')->name('add-to-cart');
    Route::post('/add-to-cart','Front\CartController@singleAddToCart')->name('single-add-to-cart');
    Route::get('cart-delete/{id}','Front\CartController@cartDelete')->name('cart-delete');
    Route::post('cart-update','Front\CartController@cartUpdate')->name('cart.update');
    
    //Route::post('cart/order','OrderController@store')->name('cart.order');
    
    // Shipping Address
    Route::resource('/shipping','Front\ShippingController');
    Route::get('/shipping/{id}/delete/', 'Front\ShippingController@destroy')->name('shipping.delete');
    Route::get('/shipping/{id}/default/', 'Front\ShippingController@addressDefault')->name('shipping.default');
    
    // Events
    Route::get('/events/upcoming-events', 'Front\EventsController@index')->name('upcoming.events.list');
    Route::get('/events/past-events', 'Front\EventsController@pastEvents')->name('past.events.list');
});

Route::group(['prefix' => '/admin'], function () {
    Auth::routes(['register'=>false]);
    // Login
    Route::get('/', 'Admin\Auth\LoginController@index');
    Route::get('/login', 'Admin\Auth\LoginController@index')->name('admin.login');
    Route::post('post-login', 'Admin\Auth\LoginController@postLogin')->name('admin.login.post'); 
    Route::post('/logout/submit', 'Admin\Auth\LoginController@logout')->name('admin.logout.submit');

    // Reset password
    Route::get('forget-password', 'Admin\Auth\ForgotPasswordController@showForgetPasswordForm')->name('admin.forget.password.get');
    Route::post('forget-password', 'Admin\Auth\ForgotPasswordController@submitForgetPasswordForm')->name('admin.forget.password.post');
    Route::get('reset-password/{token}', 'Admin\Auth\ForgotPasswordController@showResetPasswordForm')->name('admin.reset.password.get');
    Route::post('reset-password', 'Admin\Auth\ForgotPasswordController@submitResetPasswordForm')->name('admin.reset.password.post');
    
    //Loged in Admin User
    Route::middleware('auth:admin')->group(function () {
        
        Route::get('/dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
        Route::get('/profile', 'Admin\DashboardController@profile')->name('admin.profile');
        Route::get('/change-password', 'Admin\DashboardController@changePassword')->name('admin.change.password');
        //Route::get('/company123', 'Admin\DashboardController@companyprofile')->name('admin.company.profile');
        
        //Company Info
        Route::get('/company', 'Admin\ClientsController@index')->name('admin.company.index');
        Route::get('/company/{id}/edit/','Admin\ClientsController@edit')->name('admin.company.edit');
        Route::patch('/company/{id}/update/','Admin\ClientsController@update')->name('admin.company.update');
        Route::get('/company', 'Admin\ClientsController@index')->name('admin.company.index');
        Route::get('/company/logo', 'Admin\ClientsController@companylogo')->name('admin.company.logo');
        Route::post('/company/logo/store','Admin\ClientsController@fileStore')->name('admin.company.logo.store');
        Route::post('/company/images-delete', 'Admin\ClientsController@destroy')->name('admin.company.logo.delete');
        Route::get('/company/images-view', 'Admin\ClientsController@viewimage')->name('admin.company.logo.view');
        
        //Email Template
        Route::resource('/templates/email','Admin\EmailTemplatesController');
        Route::get('templates/email/{id}/edit/','Admin\EmailTemplatesController@edit');
        Route::get('templates/email/{id}/delete/', 'Admin\EmailTemplatesController@destroy')->name('email.delete'); 
        
        //Venues
        Route::resource('/events/venues','Admin\VenuesController');
        Route::get('events/venues/{id}/edit/','Admin\VenuesController@edit');
        Route::get('events/venues/{id}/status/','Admin\VenuesController@status')->name('venues.status'); 
        Route::get('events/venues/{id}/delete/', 'Admin\VenuesController@destroy')->name('venues.delete'); 
        Route::post('events/venues/{id}/change/', 'Admin\VenuesController@destroystatus')->name('venues.status.change'); 
        
        //Venues
        Route::resource('/events','Admin\EventsController');
        Route::get('events/{id}/edit/','Admin\VenuesController@edit');
        
        //Member Profile
        //Route::get('/members', 'Admin\MemberProfilesController@index')->name('admin.members.index');
        Route::resource('/members','Admin\MemberProfilesController');
        Route::get('/members/{id}/edit/','Admin\MemberProfilesController@edit')->name('admin.members.edit');
        Route::patch('/members/{id}/update/','Admin\MemberProfilesController@update')->name('admin.members.update');
    });
});


Route::group(['prefix' => '/member'], function () {
    Route::get('/login', 'Member\Auth\LoginController@showLoginForm')->name('member.login');
    Route::get('/', 'Member\Auth\LoginController@showLoginForm');
    Route::post('post-login', 'Member\Auth\LoginController@postLogin')->name('login.post'); 
    Route::post('/logout/submit', 'Member\Auth\LoginController@logout')->name('member.logout.submit');
    

resources/views/global/breadcrumb.blade.php
<div class="content-header row">
    <div class="content-header-left col-md-12 col-12 mb-2">
        <h3 class="content-header-title">@yield('title')</h3>
        <div class="row breadcrumbs-top">
            <div class="breadcrumb-wrapper col-12">
                @if(@isset($breadcrumbs))
                <ol class="breadcrumb">
                    {{-- this will load breadcrumbs dynamically from controller --}}
                    @foreach ($breadcrumbs as $breadcrumb)
                    <li class="breadcrumb-item">
                        @if(isset($breadcrumb['link']))
                        <a href="{{ $breadcrumb['link'] }}">
                            @endif
                            {{ $breadcrumb['name'] }}
                            @if(isset($breadcrumb['link']))
                        </a>
                        @endif
                    </li>
                    @endforeach
                </ol> 
                @endisset
            </div>
        </div>
    </div>
</div>

resources/views/global/footer.blade.php
<footer class="footer footer-static footer-light navbar-border navbar-shadow">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; 2021 <a class="text-bold-800 grey darken-2" href="http://businessboosters.com.my" target="_blank">Business Boosters</a>
            </span>
            <span class="float-md-right d-none d-lg-block">Powerd by Business Boosters<span id="scroll-top"></span></span></p>
    </footer>

resources/views/global/header.blade.php
<?php
$user = Auth::guard(config('auth.defaults.guard'))->user();

if($user->user_type == 'members') {
    $custroute = 'member';
}else {
    $custroute = 'admin';
}

//$user->client->image
?>
<style>
    .header-navbar .navbar-header .navbar-brand .brand-logo {
    width: auto;
    max-width: 100%;
}

//.header-navbar{overflow: hidden;}
</style>

<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light bg-info navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-lg-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item mr-auto">
                    <a class="navbar-brand" href="/">
                        
                    </a></li>
                <li class="nav-item d-none d-lg-block nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="toggle-icon ft-toggle-right font-medium-3 white" data-ticon="ft-toggle-right"></i></a></li>
                <li class="nav-item d-lg-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>


                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <span class="mr-1 user-name text-bold-700">{{ Auth::guard($custroute)->user()->full_name }}</span>
                            <span class="avatar avatar-online">
                                <img src="{{ Helper::my_avatar() }}" alt="{{ Auth::guard($custroute)->user()->full_name }}"><i></i>
                            </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{{ route($custroute.'.profile') }}"><i class="ft-user"></i> Profile</a>
                            <a class="dropdown-item" href="{{ route($custroute.'.change.password') }}"><i class="la la-key"></i> Change Password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void" onclick="$('#logout-form').submit();"><i class="ft-power"></i> Logout</a>
                            <form id="logout-form" action="{{ route($custroute.'.logout.submit') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/global/horizontalMenu.blade.php
@php
    $configData = Helper::applClasses();
@endphp
{{-- Horizontal Menu --}}
<div class="horizontal-menu-wrapper">
    <div class="header-navbar navbar-expand-sm navbar navbar-horizontal floating-nav {{($configData['theme'] === 'light') ? "navbar-light" : "navbar-dark" }} navbar-without-dd-arrow navbar-shadow navbar-brand-center" role="navigation" data-menu="menu-wrapper" data-nav="brand-center">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mr-auto"><a class="navbar-brand" href="dashboard-analytics">
                    <div class="brand-logo"></div>
                    <h2 class="brand-text mb-0">Vusax</h2></a></li>
                <li class="nav-item nav-toggle">
                    <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
                        <i class="feather icon-x d-block d-xl-none font-medium-4 primary toggle-icon"></i>
                        <i class="toggle-icon feather icon-disc font-medium-4 d-none d-xl-block collapse-toggle-icon primary" data-ticon="icon-disc"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Horizontal menu content-->
        <div class="navbar-container main-menu-content" data-menu="menu-container">
            <ul class="nav navbar-nav" id="main-menu-navigation" data-menu="menu-navigation">
                {{-- Foreach menu item starts --}}
                @foreach($menuData[1]->menu as $menu)
                    @php
                        $custom_classes = "";
                        if(isset($menu->classlist)) {
                            $custom_classes = $menu->classlist;
                        }
                        $translation = "";
                        if(isset($menu->i18n)){
                            $translation = $menu->i18n;
                        }
                    @endphp
                    <li class="dropdown nav-item {{ (request()->is($menu->url)) ? 'active' : '' }} {{ $custom_classes }}" data-menu="dropdown">
                        <a href="{{ $menu->url }}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <i class="{{ $menu->icon }}"></i>
                            <span data-i18n="{{ $translation }}">{{ $menu->name }}</span>
                        </a>
                        @if(isset($menu->submenu))
                            @include('panels/horizontalSubmenu', ['menu' => $menu->submenu])
                        @endif
                    </li>
                @endforeach
                {{-- Foreach menu item ends --}}
            </ul>
        </div>
    </div>
</div>

resources/views/global/horizontalSubmenu.blade.php
{{-- For Horizontal submenu --}}
<ul class="dropdown-menu">
    @foreach($menu as $submenu)
        <?php
            $custom_classes = "";
            if(isset($submenu->classlist)) {
                $custom_classes = $submenu->classlist;
            }
            $submenuTranslation = "";
            if(isset($menu->i18n)){
                $submenuTranslation = $menu->i18n;
            }
        ?>
        <li class="{{ (request()->is($submenu->url)) ? 'active' : '' }} {{ (isset($submenu->submenu)) ? "dropdown dropdown-submenu" : '' }} {{ $custom_classes }}">
            <a href="{{ $submenu->url }}" class="dropdown-item {{ (isset($submenu->submenu)) ? "dropdown-toggle" : '' }}" {{ (isset($submenu->submenu)) ? 'data-toggle=dropdown' : '' }}>
                <i class="{{ isset($submenu->icon) ? $submenu->icon : "" }}"></i>
                <span data-i18n="{{ $submenuTranslation }}">{{ $submenu->name }}</span>
            </a>
            @if (isset($submenu->submenu))
                @include('panels/horizontalSubmenu', ['menu' => $submenu->submenu])
            @endif
        </li>
    @endforeach
</ul>

resources/views/global/messages.blade.php
@if ($message = Session::get('success'))
<script>
    toastr['success']('{{ $message }}', 'Success!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($message = Session::get('error'))
<script>
      toastr['error']('{{ $message }}', 'Error!', {
      closeButton: true,
      tapToDismiss: false,
    });
    </script>
@endif


@if ($message = Session::get('warning'))
<script>
    toastr['warning']('{{ $message }}', 'Warning!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($message = Session::get('info'))
<script>
    toastr['info']('{{ $message }}', 'Info!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif


@if ($errors->any())
<script>
    toastr['warning']('Please check the form below for errors', 'Warning!', {
      closeButton: true,
      tapToDismiss: false,
    });
</script>
@endif

resources/views/global/scripts.blade.php
{{-- Vendor Scripts --}}
<script src="{{ asset('themes/modern-admin/app-assets/vendors/js/vendors.min.js') }}"></script>
<script src="{{ asset('themes/modern-admin/app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
@yield('vendor-script')


{{-- Theme Scripts --}}
<script src="{{ asset('themes/modern-admin/app-assets/js/core/app-menu.js') }}"></script>
<script src="{{ asset('themes/modern-admin/app-assets/js/core/app.js') }}"></script>
<script src="{{ asset('themes/modern-admin/app-assets/js/scripts/extensions/toastr.js') }}"></script>
{{-- page script --}}
@yield('page-script')
@include('global/messages')

{{-- page script --}}

resources/views/global/styles.blade.php
<!-- BEGIN: Vendor CSS-->

<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/vendors/css/vendors.min.css') }}">
<link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
 
{{-- Vendor Styles --}}
@yield('vendor-style')
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/bootstrap.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/bootstrap-extended.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/colors.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/components.css') }}">
<!-- END: Theme CSS-->

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/core/menu/menu-types/vertical-menu.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/core/colors/palette-gradient.css') }}">
<link rel="stylesheet" href="{{ asset('themes/modern-admin/app-assets/vendors/css/extensions/toastr.css') }}">

{{-- Page Styles --}}
@yield('page-style')
<!-- END: Page CSS-->

<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{{ asset('themes/modern-admin/app-assets/css/plugins/extensions/toastr.css')}}"> 
<link rel="stylesheet" href="{{ asset('themes/modern-admin/assets/css/style.css') }}" />
<!-- END: Custom CSS-->

resources/views/global/verticalMenu.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class=" nav-item"><a href="dashboard"><i class="la la-home"></i><span class="menu-title" data-i18n="Home">Dashboard</span></a></li>
            <li class="{{ (request()->is(['admin/company*'])) ? 'active' : '' }} nav-item"><a href="{{ route('admin.company.index') }}"><i class="la la-briefcase"></i><span class="menu-title" data-i18n="Home">Your Company</span></a></li>
            <li class=" nav-item"><a href="#"><i class="la la-users"></i><span class="menu-title" data-i18n="MembersAccount">Members Account</span></a>
                <ul class="menu-content">
                    <li class="{{ (request()->is(['admin/members*','client/sharings*'])) ? 'active' : '' }}"><a class="menu-item" href="{{ route('members.index') }}"><i></i><span data-i18n="Member List">Member List</span></a></li>
                    <li class="{{ (request()->is(['client/category'])) ? 'active' : '' }}"><a class="menu-item" href="{{ route('members.index') }}"><i></i><span data-i18n="Bulk">Bulk upload</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-user"></i><span class="menu-title" data-i18n="CustomerList">Customer List</span></a>
                <ul class="menu-content">
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Client List">Active</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Not active">Not active</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Payment">Payment</span></a>
                <ul class="menu-content">
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Payment Summary">Payment Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Points Summary">Points Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Payment Summary">Latest Promotion Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Points Summary">Event Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Points Expiry">Points Expiry</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Latest Promotion">Latest Promotion</span></a>
                <ul class="menu-content">
                    
                    <li class=""><a class="menu-item" href="{{route('elfinder.index') }}"><i></i><span data-i18n="Detail">Detail</span></a></li> 
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Summary">Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Completed">Completed</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Events">Events</span></a>
                <ul class="menu-content">
                    <li class="{{ (request()->is(['admin/events/venues*'])) ? 'active' : '' }}"><a class="menu-item" href="{{ route('venues.index') }}"><i></i><span data-i18n="Summary">Venues</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Summary">Summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Completed">Completed</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Report">Report</span></a>
                <ul class="menu-content">
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Member list">Member list</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Customer List">Customer List</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Member Points summary">Member Points summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Customer_Points summary">Customer_Points summary</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Customer Redemption Detail">Customer Redemption Detail</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Points">Points</span></a>
                <ul class="menu-content">
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Purchase Points">Purchase Points</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Points Purchase History">Points Purchase History</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Template">Template</span></a>
                <ul class="menu-content">
                    <li class="{{ (request()->is(['admin/templates/email*'])) ? 'active' : '' }}"><a class="menu-item" href="{{ route('email.index') }}"><i></i><span data-i18n="Email">Email</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="SMS">SMS</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Push Notification">Push Notification</span></a></li>
                </ul>
            </li>
            
            <li class=" nav-item"><a href="#"><i class="la la-money"></i><span class="menu-title" data-i18n="Roles & Permissions">Roles & Permissions</span></a>
                <ul class="menu-content">
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="All Roles">All Roles</span></a></li>
                    <li class=""><a class="menu-item" href=""><i></i><span data-i18n="Create Role">Create Role</span></a></li>
                </ul>
            </li>
            <li class="nav-item"><a href="#"><i class="la la-unlock"></i><span class="menu-title" data-i18n="Activity Log">Activity Log</span></a></li>
        </ul>
    </div>
</div>